logging:
  level:
    root: INFO

spring:
#  cloud:
#    gateway:
#      routes:
#        - id: fbresource
#          uri: http://localhost:8080/backend
#          predicates:
#            - Path=/fb/**
#        - id: angularresource
#          uri: forward:/index.html
#          predicates:
#            - Path=/**
#  cloud:
#    gateway:
#      routes:
#        - id: baeldung_route
#          uri: http://baeldung.com
#          predicates:
#            - Path=/baeldung/
#  cloud:
#    gateway:
#      routes:
#        - id: employeeModule
#          uri: forward:/test
#          predicates:
#            - Path=/employee/**
#        - id: consumerModule
#          uri: http://localhost:4200/
#          predicates:
#            - Path=/consumer/**
  h2:
    console.enabled: true
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  datasource:
    url: jdbc:h2:file:./../db/ParkplatzAppDb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  sql:
    init:
      mode: always

server:
  port: 8081